services:
  _defaults:
    autowire: true
    autoconfigure: true
  color_picker_custom_test:
    class: Tommysonsylverstone\ComposerTest\Content\Types\ColorPickerCustomTest
    tags: [{ name: "sulu.content.type", alias: "color_picker_custom_test" }]
